[package]
name = "ternoa-pallets-primitives"
version = "0.1.0"
edition = "2018"
license = "Apache 2.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Sp
sp-runtime = { git = "https://github.com/capsule-corp-ternoa/substrate", branch = "ternoa-substrate-2022-02-03", default-features = false }
sp-std = { git = "https://github.com/capsule-corp-ternoa/substrate", branch = "ternoa-substrate-2022-02-03", default-features = false }

# Rest
codec = { package = "parity-scale-codec", default-features = false, features = ["derive"], version = "2.3.1" }
serde = { optional = true, version = "1.0.132" }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
	# SP
	"sp-runtime/std",
    "sp-std/std",
	# Rest
	"codec/std",
	"serde",
	"scale-info/std",
]
