[workspace]
exclude = [
    "vendor/webpki",
    "vendor/ring",
]
members = [
    'common',
    'nft',
    'primitives',
    'mandate',
    'staking-rewards',
    'bridge',
    'marketplace',
    'auction',
    'rent',
    'tee',
]
