[workspace]
members = [
    'common',
    'associated-accounts',
    'auction',
    'capsule',
    'marketplace',
    'nft',
    'sgx',
    'timed-escrow',
    'primitives',
    'mandate',
    'staking-rewards',
]
