[workspace]
members = [
    'common',
    'auction',
    'capsule',
    'marketplace',
    'nft',
    'sgx',
    'primitives',
    'mandate',
    'staking-rewards',
    'chainbridge',
    'erc20-bridge'
]
