[workspace]
members = [
    'common',
    'associated-accounts',
    'auctions',
    'capsules',
    'marketplace',
    'nfts',
    'sgx',
    'timed-escrow',
    'primitives',
    'mandate',
    'staking-rewards',
]
