name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      CLEAN_BUILD:
        description: "Clean build"
        required: true
        type: boolean

jobs:
  build-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-21.04

    # cancel concurrent builds on the same branch
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-04-24
          components: rustfmt, llvm-tools-preview
          target: wasm32-unknown-unknown
          default: true

      - name: Cache restore
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Clean
        if: ${{ github.event.inputs.CLEAN_BUILD == 'true' }}
        run: cargo clean

      - name: Check format
        run: cargo fmt --all -- --check

      - name: Check release
        run: cargo check --release

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --release

      - name: Benchmarking
        run: >
          pushd node &&
          cargo check --features=runtime-benchmarks --release
